version: "3"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - db:mongo
    volumes:
      - "image_data:/usr/src/app/uploads"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"

  db:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"

volumes:
  db_data:
  image_data:
