version: "3"

services:
  backend:
    build: ./backend
    command: ["npm", "start"]
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:mongo
    volumes:
      - "image_data:/ng-app/uploads"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"

volumes:
  db_data:
  image_data:
