version: "3"

services:
  web:
    build: .
    command: ["npm", "start"]
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:mongo
    volumes:
      - "image_data:/usr/src/app/uploads"

  db:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"

volumes:
  db_data:
  image_data:
